

pipeline:
  build:
    image: node:alpine
    commands:
      - yarn
      - yarn test
      - yarn build

  release:
    image: plugins/github-release
    files: dist/*
    secrets: [ api_key ]
    when:
      event: tag
