  kind: pipeline
  name: dronereact

  steps:
  - name: build
    image: node:8.16.1-alpine
    commands:
    - npm install
    - npm build

  - name: test
    image: node:8.16.1-alpine
    commands:
    - npm run test


  - name: prerelease
    image: node:8.16.1-alpine
    commands:
    - tar -zcvf build.tar.gz -C build .

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: dronekey
      files: build.tar.gz
    when:
      event: tag

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: drone-kevincardon
    when:
      status: [ success, failure ]

  trigger:
    branch:
    - master