

pipeline:
  deps:
   image: plugins/git
   commands:
     - git clone https://github.com/Lowess/devops-360-ci-cd.git

  build:
    image: node:alpine
    commands:
      - ls -al /drone/src/github.com/Lowess/*
      - yarn
      - yarn test
      - yarn build

  release:
    image: plugins/github-release
    environement:
      - PLUGIN_API_KEY=<github_token>
    secrets: [ github_token ]
    when:
      event: tag

  notify:
    image: plugins/slack
    environement:
      - SLACK_WEBHOOK=<slack_webhook>
    channel: drone
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]