

pipeline:
  deps:
    image: plugins/git
    commands:
      - git clone https://github.com/Lowess/devops-360-ci-cd.git

  build:
    image: node:alpine
    commands:
      - yarn
      - yarn test

  pre-release:
    image: node:alpine
    commands:
      - yarn build
      - tar -zcvf build.tar.gz -C build .
    when:
      event: tag

  release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - build.tar.gz
    when:
      event: tag

  deploy:
    image: lowess/drone-ansible
    pull: true
    inventory: devops-360-ci-cd/ansible/inventories/vms
    playbook: devops-360-ci-cd/ansible/spa-deploy.yml
    secrets: [ ansible_private_key ]
    when:
      event: tag

  notify:
    image: plugins/slack
    channel: drone
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]