

pipeline:
  deps:
    image: plugins/git
    commands:
      - git clone https://github.com/Lowess/devops-360-ci-cd.git

  # build:
  #   image: node:alpine
  #   commands:
  #     - yarn
  #     - yarn test
  #     - yarn build
  #     - tar -zcvf build.tar.gz -C build .

  # release:
  #   image: plugins/github-release
  #   environement:
  #     - PLUGIN_API_KEY=<github_token>
  #   secrets: [ github_token ]
  #   files:
  #     - build.tar.gz
  #   when:
  #     event: tag

  deploy:
    image: lowess/drone-ansible
    environement:
      - PLUGIN_SSH_PRIVATE_KEY=<ansible_ssh_key>
    inventory: devops-360-ci-cd/ansible/inventories/vms
    playbook: devops-360-ci-cd/ansible/spa.yml
    tags: spa
    secrets: [ ansible_ssh_key ]

  # notify:
  #   image: plugins/slack
  #   environement:
  #     - SLACK_WEBHOOK=<slack_webhook>
  #   channel: drone
  #   secrets: [ slack_webhook ]
  #   when:
  #     status: [ success, failure ]