

pipeline:
  build:
    image: node:alpine
    commands:
      - yarn
      - yarn test
      - yarn build

  release:
    image: plugins/github-release
    tag: v-${DRONE_BUILD_NUMBER}
    files: dist/*
    secrets: [ api_key ]
