---

kind: pipeline
name: react-build

steps:
  - name: deps
    image: plugins/git
    commands:
      - git clone https://github.com/Lowess/devops-360-ci-cd.git

  - name: build
    image: node:9-alpine
    commands:
      - yarn

  - name: test
    image: node:9-alpine
    commands:
      - yarn test

  - name: pre-release
    image: node:9-alpine
    commands:
      - yarn build
      - tar -zcvf build.tar.gz -C build .
    when:
      event: tag

  - name: release
    image: plugins/github-release
    settings:
      token:
        from_secret: github_token
      files:
        - build.tar.gz
    when:
      event: tag

  - name: deploy
    image: lowess/drone-ansible
    pull: true
    settings:
      inventory: devops-360-ci-cd/ansible/inventories/vms
      playbook: devops-360-ci-cd/ansible/deploy.yml
      private_key:
        from_secret: ansible_private_key
    when:
      event: tag

  - name: notify
    image: plugins/slack
    settings:
      channel: drone
      webhook:
        from_secret: slack_webhook
    when:
      status: [ success, failure ]
