---

kind: pipeline
name: react-build

steps:
  - name: deps
    image: plugins/git
    commands:
      - git clone https://github.com/Lowess/devops-360-ci-cd.git
      - cd devops-360-ci-cd
      - git checkout stable

  - name: build
    image: node:9-alpine
    commands:
      - yarn

  - name: test
    image: node:9-alpine
    commands:
      - yarn test

  - name: pre-release
    image: node:9-alpine
    commands:
      - yarn build
      - tar -zcvf build.tar.gz -C build .
    when:
      event: tag

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - build.tar.gz
    when:
      event: tag

  - name: deploy
    image: lowess/drone-ansible
    pull: true
    settings:
      inventory: devops-360-ci-cd/ansible/inventories/aws
      playbook: devops-360-ci-cd/ansible/deploy.yml
      private_key:
        from_secret: ansible_private_key
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_SECURITY_TOKEN:
        from_secret: aws_session_token
    when:
      event: tag

  - name: notify
    image: plugins/slack
    settings:
      channel: drone
      icon_url: https://seeklogo.com/images/D/drone-logo-5F31BBFE5F-seeklogo.com.png
      webhook:
        from_secret: slack_webhook
    when:
      status: [ success, failure ]
