

pipeline:
  build:
    image: node:alpine
    commands:
      - yarn
      - yarn test
      - yarn build

  release:
    image: plugins/github-release
    api_key: <github_token>
    files: dist/*
    secrets: [ github_token ]
    when:
      event: tag
