pipeline:

  steps:
  - name: build
    image: node:9.0.0
    commands:
    - npm install
    - npm build

  - name: test
    image: node:9.0.0
    commands:
    - npm run test

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: drone-kevincardon
    when:
      status: [ success, failure ]

  trigger:
    branch:
    - master