pipeline:

  steps:
  - name: build
    image: node:9.0.0
    commands:
    - npm install
    - npm build

  - name: test
    image: node:9.0.0
    commands:
    - npm run test


  slack-notification:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    username: dronereact
    icon_emoji: ":rocket:"
    when:
      event: [ push, tag, deployment, pull_request ]
      status: [ success, failure ]